[book]
authors = ["HQS Quantum Simulations", "Rolando Reiner"]
language = "en"
multilingual = false
src = "src"
title = "HQS qoqo-iqm User Documentation"

[preprocessor.katex]

[output.katex]

[output.html]
mathjax-support = true
